project 'Login - FireBase.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Login - FireBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Login - FireBase
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
end
